name: Deploy Node.js App
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'  # Ajuste a versão do Node.js conforme seu projeto
    - name: Install dependencies
      run: npm install
      working-directory: ./App-Web/archfacts # Ajuste o caminho para o diretório do seu projeto, se necessário
    - name: Build the app
      run: npm run dev
      working-directory: ./App-Web/archfacts # Ajuste o caminho, se necessário
    - name: Deploy to Azure
      working-directory: ./App-Web/archfacts # Ajuste conforme o caminho do seu projeto