name: CI/CD pipeline for Frontend with React and Vite (ArchFacts)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
  test:
    runs on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4

      - name: Run Tests
        run: test --if-present
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: 18

      - name: Build Project
        run: npm run build

      - name: Upload and Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-frontend
    - name: Install and test
      run: |
        npm ci
        npm test
      working-directory: ./archfacts

  docker:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

@@ -55,5 +49,7 @@ jobs:
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with: 
          context: ./archfacts                      
          file: ./archfacts/Dockerfile      
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/archfacts-frontend:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/archfacts-frontend:latest