name: Build and deploy Node.js app to Azure Web App - ArchFacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run dev
        working-directory: .././archfacts # Ajuste o caminho corretamente

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: .././archfacts  # Ajuste o caminho corretamente

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production' 
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8EE3270DE4764374818F54F3BA3FF401 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA21A24E42754D928C6B9D6EDFD43EFD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA61AD7FA8B04A03B53D1A087E2E9F7E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ArchFacts'
          slot-name: 'Production'
          package: .
